name: kyeol_app
description: A new Flutter discipline web app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 날짜와 데이터 저장을 위해 반드시 필요합니다.
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # 아이콘 파일이 있다면 아래 주석을 풀고 경로를 맞추세요.
  # assets:
  #   - assets/icon/icon.png
